<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 .\crazyflie1.gltf
-->

<script>
	import { Group, PerspectiveCamera } from 'three';

	import { T, useTask } from '@threlte/core';
	import { useGltf, useGltfAnimations, OrbitControls } from '@threlte/extras';

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	ref = new Group();

	const gltf = useGltf('/src/lib/assets/3d/crazyflie.glb');

	export const { actions, mixer } = useGltfAnimations(gltf, ref);

  //Propeller animation
  let propRotation = $state(0);
  let rotation = $state(0);
  useTask((delta) => {
    rotation += delta * 0.2;
  })

</script>

<T.PerspectiveCamera makeDefault position={[1.5, 1.4, 4.2]} fov={40}>
  <OrbitControls enableZoom={false} enablePan={false} />
</T.PerspectiveCamera>

<T.DirectionalLight position={[3, 3, 5]} />
<T.AmbientLight intensity={0.5} />


<T is={ref} dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group name="Scene">
			<T.Mesh
				name="pcb_Default_sldprt"
				geometry={gltf.nodes.pcb_Default_sldprt.geometry}
				material={gltf.materials['Material.003']}
				position={[0.01, 0, 0]}
				scale={0.03}
        rotation={[0, -rotation, 0]}
			>
				<T.Mesh
					name="propeller_ccw_Default_sldprt001"
					geometry={gltf.nodes.propeller_ccw_Default_sldprt001.geometry}
					material={gltf.materials['Material.004']}
					position={[33.94, 15.2, 33.85]}
					rotation={[1.56, -0.01, propRotation - 1]}
				/>
				<T.Mesh
					name="propeller_ccw_Default_sldprt002"
					geometry={gltf.nodes.propeller_ccw_Default_sldprt002.geometry}
					material={gltf.materials['Material.007']}
					position={[33.94, 15.2, -33.85]}
					rotation={[-1.56, 0.01, -propRotation + 2]}
					scale={-1}
				/>
				<T.Mesh
					name="propeller_ccw_Default_sldprt003"
					geometry={gltf.nodes.propeller_ccw_Default_sldprt003.geometry}
					material={gltf.materials['Material.004']}
					position={[-33.83, 15.2, 33.32]}
					rotation={[-1.56, 0.01, -propRotation + 5]}
					scale={-1}
				/>
				<T.Mesh
					name="7mm_motor_mount_Default_sldprt"
					geometry={gltf.nodes['7mm_motor_mount_Default_sldprt'].geometry}
					material={gltf.materials['Material.001']}
					position={[-33.72, 3.79, -33.71]}
					rotation={[1.56, 0, 0]}
				/>
				<T.Mesh
					name="7x15_motor_Default_sldprt"
					geometry={gltf.nodes['7x15_motor_Default_sldprt'].geometry}
					material={gltf.materials['Material.002']}
					position={[-33.85, -4.25, -33.74]}
					rotation={[1.56, 0, 0]}
				/>
				<T.Mesh
					name="battery_bc-bl-01-a_Default_sldprt"
					geometry={gltf.nodes['battery_bc-bl-01-a_Default_sldprt'].geometry}
					material={gltf.materials['Material.006']}
					position={[-11.27, 2.54, 8.16]}
					rotation={[1.56, 0, 0]}
				/>
				<T.Mesh
					name="battery_holder_board_Default_sldprt"
					geometry={gltf.nodes.battery_holder_board_Default_sldprt.geometry}
					material={gltf.materials['Material.003']}
					position={[-10.37, 9.9, 13.13]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={[1, 0.97, 1]}
				/>
				<T.Mesh
					name="header_Default_sldprt"
					geometry={gltf.nodes.header_Default_sldprt.geometry}
					material={gltf.materials['Material.005']}
					position={[-9.32, 4.28, -8.95]}
					rotation={[1.56, 0, -Math.PI]}
					scale={-1}
				/>
				<T.Mesh
					name="propeller_ccw_Default_sldprt004"
					geometry={gltf.nodes.propeller_ccw_Default_sldprt004.geometry}
					material={gltf.materials['Material.004']}
					position={[-33.94, 15.2, -33.85]}
					rotation={[1.57, 0, propRotation]}
				/>
			</T.Mesh>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T>
