<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 .\stingray.glb
-->

<script>
  import { T, useTask } from '@threlte/core'
  import { useGltf, OrbitControls } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('src/lib/assets/3d/stingray.glb')

  //Animation
  let propRotation = $state(0);
  let rotation = $state(0);
  useTask((delta) => {
    rotation += delta * 0.2;
  })

</script>

<T.PerspectiveCamera makeDefault position={[-20,15,-50]} fov={40}>
<OrbitControls enableZoom={false} enablePan={false} />
</T.PerspectiveCamera>

<T.DirectionalLight position={[-30, 9, -15]} intensity={4} />
<T.AmbientLight intensity={1.5} />


<T.Group
  bind:ref
  dispose={false}
  {...props}
  rotation={[0,-rotation,0]}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.FUS_1_.geometry}
      material={gltf.materials['ABS Plastic']}
      position={[-0.84, 3.05, -13.04]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.05}
    />
    <T.Mesh
      geometry={gltf.nodes.FUS_2.geometry}
      material={gltf.materials['ABS Plastic']}
      position={[-0.84, 3.04, -6.94]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.05}
    />
    <T.Mesh
      geometry={gltf.nodes.FUS_3.geometry}
      material={gltf.materials['ABS Plastic']}
      position={[-0.85, 3.07, 0.47]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.05}
    />
    <T.Mesh
      geometry={gltf.nodes.FUS_4.geometry}
      material={gltf.materials['ABS Plastic']}
      position={[-0.84, 2.52, 7.72]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.05}
    />
    <T.Mesh
      geometry={gltf.nodes.BATTERY_PAD.geometry}
      material={gltf.materials['ABS Plastic']}
      position={[-0.81, 1.53, -9.59]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.05}
    />
    <T.Mesh
      geometry={gltf.nodes.NOSE.geometry}
      material={gltf.materials['ABS Plastic']}
      position={[-0.84, 2.8, -17.6]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.05}
    />
    <T.Mesh
      geometry={gltf.nodes.NOSE_VTX_COVER.geometry}
      material={gltf.materials['ABS Plastic']}
      position={[-0.83, 3.76, -17.48]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.05}
    />
    <T.Group
      position={[-0.89, 2.63, 10.43]}
      rotation={[Math.PI / 2, -0.66, 0]}
      scale={0.52}
    >
      <T.Mesh
        geometry={gltf.nodes.drone_motor_1.geometry}
        material={gltf.materials['Opaque(250,182,1)']}
      />
      <T.Mesh
        geometry={gltf.nodes.drone_motor_2.geometry}
        material={gltf.materials['Opaque(168,13,119)']}
      />
      <T.Mesh
        geometry={gltf.nodes.drone_motor_3.geometry}
        material={gltf.materials['Opaque(25,25,25)']}
      />
      <T.Mesh
        geometry={gltf.nodes.drone_motor_4.geometry}
        material={gltf.materials['Opaque(248,135,1)']}
      />
      <T.Mesh
        geometry={gltf.nodes.drone_motor_5.geometry}
        material={gltf.materials['Opaque(234,234,234)']}
      />
      <T.Mesh
        geometry={gltf.nodes.drone_motor_6.geometry}
        material={gltf.materials['Opaque(98,157,155)']}
      />
      <T.Mesh
        geometry={gltf.nodes.drone_motor_7.geometry}
        material={gltf.materials['Opaque(106,97,100)']}
      />
      <T.Mesh
        geometry={gltf.nodes.drone_motor_8.geometry}
        material={gltf.materials['Opaque(42,61,67)']}
      />
      <T.Mesh
        geometry={gltf.nodes.drone_motor_9.geometry}
        material={gltf.materials['Opaque(181,183,178)']}
      />
      <T.Mesh
        geometry={gltf.nodes.drone_motor_10.geometry}
        material={gltf.materials['Opaque(170,61,67)']}
      />
      <T.Mesh
        geometry={gltf.nodes.drone_motor_11.geometry}
        material={gltf.materials['Opaque(255,38,130)']}
      />
      <T.Mesh
        geometry={gltf.nodes.drone_motor_12.geometry}
        material={gltf.materials['166,164,163']}
      />
      <T.Mesh
        geometry={gltf.nodes.drone_motor_13.geometry}
        material={gltf.materials['Opaque(87,84,85)']}
      />
      <T.Mesh
        geometry={gltf.nodes.drone_motor_14.geometry}
        material={gltf.materials['Opaque(188,73,169)']}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.MOTOR_MOUNT_D19.geometry}
      material={gltf.materials['ABS Plastic']}
      position={[-0.83, 2.72, 9.69]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.05}
    />
    <T.Mesh
      geometry={gltf.nodes.WINGTIP_L_1.geometry}
      material={gltf.materials['ABS Plastic']}
      position={[-26.83, 3.23, 6.49]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.05}
    />
    <T.Mesh
      geometry={gltf.nodes.AIL_1_L_.geometry}
      material={gltf.materials['ABS Plastic']}
      position={[-14.91, 2.73, 7.29]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.05}
    />
    <T.Mesh
      geometry={gltf.nodes.AIL_2_L.geometry}
      material={gltf.materials['ABS Plastic']}
      position={[-22.14, 2.9, 10.36]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.05}
    />
    <T.Mesh
      geometry={gltf.nodes.WING_1_L.geometry}
      material={gltf.materials['ABS Plastic']}
      position={[-15.57, 2.89, 1.06]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.05}
    />
    <T.Mesh
      geometry={gltf.nodes.WING_2_L.geometry}
      material={gltf.materials['ABS Plastic']}
      position={[-22.44, 2.91, 3.99]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.05}
    />
    <T.Mesh
      geometry={gltf.nodes.WING_ROOT_L.geometry}
      material={gltf.materials['ABS Plastic']}
      position={[-11.07, 2.97, -0.89]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.05}
    />
    <T.Mesh
      geometry={gltf.nodes.WINGTIP_L_1001.geometry}
      material={gltf.materials['ABS Plastic']}
      position={[25.17, 3.23, 6.49]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={-0.05}
    />
    <T.Mesh
      geometry={gltf.nodes.AIL_1_L_001.geometry}
      material={gltf.materials['ABS Plastic']}
      position={[13.24, 2.73, 7.29]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={-0.05}
    />
    <T.Mesh
      geometry={gltf.nodes.AIL_2_L001.geometry}
      material={gltf.materials['ABS Plastic']}
      position={[20.47, 2.9, 10.36]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={-0.05}
    />
    <T.Mesh
      geometry={gltf.nodes.WING_1_L001.geometry}
      material={gltf.materials['ABS Plastic']}
      position={[13.9, 2.89, 1.06]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={-0.05}
    />
    <T.Mesh
      geometry={gltf.nodes.WING_2_L001.geometry}
      material={gltf.materials['ABS Plastic']}
      position={[20.78, 2.91, 3.99]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={-0.05}
    />
    <T.Mesh
      geometry={gltf.nodes.WING_ROOT_L001.geometry}
      material={gltf.materials['ABS Plastic']}
      position={[9.41, 2.97, -0.89]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={-0.05}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
